SELECT H.HISTORY_ID, ROUND((100 - IFNULL(DISCOUNT_RATE, 0)) / 100 * DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID = H.CAR_ID AND C.CAR_TYPE = '트럭'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE = P.CAR_TYPE AND DATEDIFF(END_DATE, START_DATE) + 1 >= CAST(p.DURATION_TYPE AS UNSIGNED)
GROUP BY H.HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC;