WITH RECURSIVE TIME_HOUR AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM+1
    FROM TIME_HOUR
    WHERE NUM < 23
)
SELECT TIME_HOUR.NUM, IFNULL(OUTS.COUNT, 0)
FROM TIME_HOUR 
LEFT JOIN (SELECT HOUR(DATETIME) AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
ORDER BY HOUR) AS OUTS ON TIME_HOUR.NUM = OUTS.HOUR;

WITH RECURSIVE cte AS (
    SELECT 0 AS num
    UNION ALL
    SELECT num+1
    FROM cte
    WHERE num < 23
)

SELECT cte.num, IFNULL(a.입양횟수, 0)
FROM cte
LEFT JOIN (SELECT HOUR(datetime) 시간대, COUNT(*) 입양횟수
           FROM animal_outs
           GROUP BY 시간대
           ORDER BY 시간대) a
ON cte.num = a.시간대;